/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.test.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.test.model.CourseSession;
import com.test.model.CourseSessionModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CourseSession service. Represents a row in the &quot;vc_CourseSession&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CourseSessionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CourseSessionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CourseSessionImpl
 * @generated
 */
@JSON(strict = true)
public class CourseSessionModelImpl
	extends BaseModelImpl<CourseSession> implements CourseSessionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a course session model instance should use the <code>CourseSession</code> interface instead.
	 */
	public static final String TABLE_NAME = "vc_CourseSession";

	public static final Object[][] TABLE_COLUMNS = {
		{"courseSessionId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"title", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"dueDate", Types.TIMESTAMP},
		{"courseId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("courseSessionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dueDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("courseId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table vc_CourseSession (courseSessionId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,title VARCHAR(75) null,description VARCHAR(75) null,dueDate DATE null,courseId LONG)";

	public static final String TABLE_SQL_DROP = "drop table vc_CourseSession";

	public static final String ORDER_BY_JPQL =
		" ORDER BY courseSession.courseSessionId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY vc_CourseSession.courseSessionId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COURSEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COURSESESSIONID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CourseSessionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _courseSessionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCourseSessionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _courseSessionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CourseSession.class;
	}

	@Override
	public String getModelClassName() {
		return CourseSession.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CourseSession, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CourseSession, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CourseSession, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CourseSession)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CourseSession, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CourseSession, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CourseSession)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CourseSession, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CourseSession, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<CourseSession, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CourseSession, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CourseSession, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<CourseSession, Object>>();
		Map<String, BiConsumer<CourseSession, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<CourseSession, ?>>();

		attributeGetterFunctions.put(
			"courseSessionId", CourseSession::getCourseSessionId);
		attributeSetterBiConsumers.put(
			"courseSessionId",
			(BiConsumer<CourseSession, Long>)CourseSession::setCourseSessionId);
		attributeGetterFunctions.put("groupId", CourseSession::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<CourseSession, Long>)CourseSession::setGroupId);
		attributeGetterFunctions.put("companyId", CourseSession::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<CourseSession, Long>)CourseSession::setCompanyId);
		attributeGetterFunctions.put("userId", CourseSession::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<CourseSession, Long>)CourseSession::setUserId);
		attributeGetterFunctions.put("userName", CourseSession::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<CourseSession, String>)CourseSession::setUserName);
		attributeGetterFunctions.put(
			"createDate", CourseSession::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<CourseSession, Date>)CourseSession::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", CourseSession::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<CourseSession, Date>)CourseSession::setModifiedDate);
		attributeGetterFunctions.put("title", CourseSession::getTitle);
		attributeSetterBiConsumers.put(
			"title",
			(BiConsumer<CourseSession, String>)CourseSession::setTitle);
		attributeGetterFunctions.put(
			"description", CourseSession::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<CourseSession, String>)CourseSession::setDescription);
		attributeGetterFunctions.put("dueDate", CourseSession::getDueDate);
		attributeSetterBiConsumers.put(
			"dueDate",
			(BiConsumer<CourseSession, Date>)CourseSession::setDueDate);
		attributeGetterFunctions.put("courseId", CourseSession::getCourseId);
		attributeSetterBiConsumers.put(
			"courseId",
			(BiConsumer<CourseSession, Long>)CourseSession::setCourseId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getCourseSessionId() {
		return _courseSessionId;
	}

	@Override
	public void setCourseSessionId(long courseSessionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_courseSessionId = courseSessionId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@JSON
	@Override
	public Date getDueDate() {
		return _dueDate;
	}

	@Override
	public void setDueDate(Date dueDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dueDate = dueDate;
	}

	@JSON
	@Override
	public long getCourseId() {
		return _courseId;
	}

	@Override
	public void setCourseId(long courseId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_courseId = courseId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCourseId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("courseId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CourseSession.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CourseSession toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CourseSession>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CourseSessionImpl courseSessionImpl = new CourseSessionImpl();

		courseSessionImpl.setCourseSessionId(getCourseSessionId());
		courseSessionImpl.setGroupId(getGroupId());
		courseSessionImpl.setCompanyId(getCompanyId());
		courseSessionImpl.setUserId(getUserId());
		courseSessionImpl.setUserName(getUserName());
		courseSessionImpl.setCreateDate(getCreateDate());
		courseSessionImpl.setModifiedDate(getModifiedDate());
		courseSessionImpl.setTitle(getTitle());
		courseSessionImpl.setDescription(getDescription());
		courseSessionImpl.setDueDate(getDueDate());
		courseSessionImpl.setCourseId(getCourseId());

		courseSessionImpl.resetOriginalValues();

		return courseSessionImpl;
	}

	@Override
	public CourseSession cloneWithOriginalValues() {
		CourseSessionImpl courseSessionImpl = new CourseSessionImpl();

		courseSessionImpl.setCourseSessionId(
			this.<Long>getColumnOriginalValue("courseSessionId"));
		courseSessionImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		courseSessionImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		courseSessionImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		courseSessionImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		courseSessionImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		courseSessionImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		courseSessionImpl.setTitle(
			this.<String>getColumnOriginalValue("title"));
		courseSessionImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		courseSessionImpl.setDueDate(
			this.<Date>getColumnOriginalValue("dueDate"));
		courseSessionImpl.setCourseId(
			this.<Long>getColumnOriginalValue("courseId"));

		return courseSessionImpl;
	}

	@Override
	public int compareTo(CourseSession courseSession) {
		long primaryKey = courseSession.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CourseSession)) {
			return false;
		}

		CourseSession courseSession = (CourseSession)object;

		long primaryKey = courseSession.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CourseSession> toCacheModel() {
		CourseSessionCacheModel courseSessionCacheModel =
			new CourseSessionCacheModel();

		courseSessionCacheModel.courseSessionId = getCourseSessionId();

		courseSessionCacheModel.groupId = getGroupId();

		courseSessionCacheModel.companyId = getCompanyId();

		courseSessionCacheModel.userId = getUserId();

		courseSessionCacheModel.userName = getUserName();

		String userName = courseSessionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			courseSessionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			courseSessionCacheModel.createDate = createDate.getTime();
		}
		else {
			courseSessionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			courseSessionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			courseSessionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		courseSessionCacheModel.title = getTitle();

		String title = courseSessionCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			courseSessionCacheModel.title = null;
		}

		courseSessionCacheModel.description = getDescription();

		String description = courseSessionCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			courseSessionCacheModel.description = null;
		}

		Date dueDate = getDueDate();

		if (dueDate != null) {
			courseSessionCacheModel.dueDate = dueDate.getTime();
		}
		else {
			courseSessionCacheModel.dueDate = Long.MIN_VALUE;
		}

		courseSessionCacheModel.courseId = getCourseId();

		return courseSessionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CourseSession, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CourseSession, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CourseSession, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((CourseSession)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CourseSession, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CourseSession, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CourseSession, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CourseSession)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CourseSession>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					CourseSession.class, ModelWrapper.class);

	}

	private long _courseSessionId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _title;
	private String _description;
	private Date _dueDate;
	private long _courseId;

	public <T> T getColumnValue(String columnName) {
		Function<CourseSession, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CourseSession)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("courseSessionId", _courseSessionId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("dueDate", _dueDate);
		_columnOriginalValues.put("courseId", _courseId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("courseSessionId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("title", 128L);

		columnBitmasks.put("description", 256L);

		columnBitmasks.put("dueDate", 512L);

		columnBitmasks.put("courseId", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CourseSession _escapedModel;

}